on: [push]
jobs:
  build-shallow-expr:
    runs-on: ubuntu-latest
    name: Build Shallow-Expressions
    steps:
      - uses: actions/checkout@v3
      - uses: lexbailey/isabelle-theory-build-github-action@v6
        with:
          isabelle-version: '2021-1'
          depends: 'https://github.com/isabelle-utp/Z_Toolkit.git@main'
          session-name: 'Shallow-Expressions Shallow-Expressions-Z'
          theory-root: '. Z'
          report_url: 'https://isabelle-utp-ci-dashboard.link/submit_job_log'
          report_secret: ${{ secrets.DashboardReportKey }}

